import { Inter } from "next/font/google";
import { type Metadata } from "next";

import "@/common/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const RootLayout: LayoutType = ({ children }) => (
  <html lang='en'>
    <body className={inter.className}>{children}</body>
  </html>
);

export default RootLayout;
