import { type Metadata } from "next";

import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const RootLayout: LayoutType = ({ children }) => <main className={styles.main}>{children}</main>;

export default RootLayout;
