import { type Metadata } from "next";
import { FC, PropsWithChildren } from "react";

import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => <main className={styles.main}>{children}</main>;

export default RootLayout;
